demo:
    build: ./demo
    volumes:
        - ./demo/home:/home/demo:ro
        - ./demo/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10100:4597"
    expose:
        - "4597"

bof:
    build: ./baby_bof
    volumes:
        - ./baby_bof/home:/home/baby_bof:ro
        - ./baby_bof/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10102:4597"
    expose:
        - "4597"


luck:
    build: ./luck
    volumes:
        - ./luck/home:/home/luck:ro
        - ./luck/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10101:4597"
    expose:
        - "4597"

shellcode:
    build: ./shellcode
    volumes:
        - ./shellcode/home:/home/shellcode:ro
        - ./shellcode/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10103:4597"
    expose:
        - "4597"

shellcode_revenge:
    build: ./shellcode_revenge
    volumes:
        - ./shellcode_revenge/home:/home/shellcode_revenge:ro
        - ./shellcode_revenge/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10104:4597"
    expose:
        - "4597"

rop:
    build: ./rop
    volumes:
        - ./rop/home:/home/rop:ro
        - ./rop/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10105:4597"
    expose:
        - "4597"

ret2libc:
    build: ./ret2libc
    volumes:
        - ./ret2libc/home:/home/ret2libc:ro
        - ./ret2libc/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10106:4597"
    expose:
        - "4597"

end:
    build: ./end
    volumes:
        - ./end/home:/home/end:ro
        - ./end/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10108:4597"
    expose:
        - "4597"

ncu_center:
    build: ./ncu_center
    volumes:
        - ./ncu_center/home:/home/ncu_center:ro
        - ./ncu_center/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10107:4597"
    expose:
        - "4597"

rop_revenge:
    build: ./rop_revenge
    volumes:
        - ./rop_revenge/home:/home/rop_revenge:ro
        - ./rop_revenge/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10109:4597"
    expose:
        - "4597"

shellcode_revenge_plus_plus:
    build: ./shellcode_revenge++
    volumes:
        - ./shellcode_revenge++/home:/home/shellcode_revenge++:ro
        - ./shellcode_revenge++/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10110:4597"
    expose:
        - "4597"

baby_ghost:
    build: ./baby_ghost
    volumes:
        - ./baby_ghost/home:/home/baby_ghost:ro
        - ./baby_ghost/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10111:4597"
    expose:
        - "4597"